#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidNativeAppWithCSharp.Resource", IsApplication=true)]

namespace AndroidNativeAppWithCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int breakTimeChoicesLeftWrapper = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int breakTimeChoicesRightWrapper = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int btnsWrapper = 2131099664;
			
			// aapt resource value: 0x7f060003
			public const int centralInfoWrapper = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int currentTime = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int currentTimeLbl = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int currentTimeWrapper = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int fifteenMinLbl = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int fiveMinLbl = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int message = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int messageWrapper = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int offCheckbox = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int pomodoroClockWrapper = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int pomodoroLbl = 2131099656;
			
			// aapt resource value: 0x7f060014
			public const int progressBar = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int progressBarWrapper = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int progressMessage = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int runningCheckbox = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int startBtn = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int stopBtn = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int thirtyMinLbl = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int threeMinLbl = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
